# Use a imagem oficial do .NET SDK
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copie os arquivos de projeto e restaure as dependências
COPY ControledeContatos/*.csproj ./ControledeContatos/
RUN dotnet restore ./ControledeContatos/*.csproj

# Copie o restante dos arquivos e compile o projeto
COPY . .
WORKDIR /app/ControledeContatos
RUN dotnet publish -c Release -o out

# Use a imagem oficial do .NET Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/ControledeContatos/out .

# Exponha a porta e inicie o aplicativo
EXPOSE 80
ENTRYPOINT ["dotnet", "ControledeContatos.dll"]
