[build]
builder = "dockerfile"
dockerfilePath = "./ControledeContatos/dockerfile"

[deploy]
startCommand = "dotnet ControledeContatos.dll"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"
